language: ruby

rvm:
  - ruby-head
  - 2.2.2
  - 2.1.6
  - 2.0.0

before_install:
  - "sudo apt-get install libzmq3-dev"
  - "sudo pip install 'ipython[notebook]'"

script: bundle exec rake

notifications:
  irc: "chat.freenode.net#sciruby"